app2/urls.py
from django.urls import path
from app2.views import *
app_name='tarak'
urlpatterns=[
    path('a1_hai/',a1_hai,name='a1_hai'),
    path('a1_hello/',a1_hello,name='a1_hello'),
]

project10/urls.py
from django.contrib import admin
from django.urls import path,include
from app1.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('hai/',hai,name='hai'),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def hai(request):
    return render(request,'hai.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def a1_hai(request):
    return render(request,'a1_hai.html')

def a1_hello(request):
    return render(request,'a1_hello.html')

templates/a1_hai.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>This is specific urls mapping of a1_hai html page</h1>
        <h1><a href="{% url 'hai' %}">This is mapping to hai html page</a></h1>
        <h1><a href="{% url 'tarak:a1_hello' %}">This is mapping to a1_hello html page</a></h1>
    </center>
</body>
</html>

templates/a1_hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   <center>
    <h1>This is specific urls mapping of a1_hello html page</h1>
    <h1><a href="{% url 'hai' %}">This is mapping to hai html page</a></h1>
    <h1><a href="{% url 'tarak:a1_hai' %}">This is mapping to a1_hai html page</a></h1>
   </center> 
</body>
</html>

templates/hai.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>This is generic url mapping</h1>
        <h1><a href="{% url 'tarak:a1_hai' %}">It is mapping to a1_hai html page </a></h1>
        <h1><a href="{% url 'tarak:a1_hello' %}">It is mapping to a1_hello html page</a></h1>
    </center>
</body>
</html>